"""Initial migration.

Revision ID: 796e3e328520
Revises: 
Create Date: 2024-11-05 17:26:44.191913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796e3e328520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(length=15), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=160), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('responder')
    op.drop_table('emergency_request')
    # ### end Alembic commands ###
